# Default values for dsb-client-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

clientgateway:
  config:
    port: 3000
    natsClusterUrl: nats://dsb-nats.dsb.svc:4222

image:
  # repository: 098061033856.dkr.ecr.us-east-1.amazonaws.com/ew-dos-dsb-ecr
  repository: aemocontainerregistry.azurecr.io/dsb/client-gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: canary
