name: Pull Request

on:
  pull_request:

jobs:
  build-api:
    uses: ./.github/workflows/build_api.yml
    secrets:
      ONEPASSWORD_VAULT_ID: ${{ secrets.ONEPASSWORD_VAULT_ID }}
      ONEPASSWORD_HOST: ${{ secrets.ONEPASSWORD_HOST }}
      ONEPASSWORD_TOKEN: ${{ secrets.ONEPASSWORD_TOKEN }}
  lint-commits:
    uses: ./.github/workflows/commitlint.yml
  build-frontend:
    uses: ./.github/workflows/build_frontend.yml
  build-scheduler:
    uses: ./.github/workflows/build_scheduler.yml
